inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/**/**/*'
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'

Lint/Void:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - 'app/controllers/homepage_controller.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/I18nLocaleAssignment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/creator.rb'

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: never

Style/Semicolon:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
