# frozen_string_literal: true
require 'simplecov'

SimpleCov.formatter = Coveralls::SimpleCov::Formatter
SimpleCov.start do
  # Ignore files automatically generated by Rails
  add_filter 'channel.rb'
  add_filter 'connection.rb'
  add_filter 'application_job'
  add_filter 'application_mailer'

  # Ignore files automatically generated by Hyrax
  add_filter 'qa.rb'
  add_filter 'local_authority.rb'
  add_filter 'local_authority_entry.rb'
end
