terms:
  - id: 'Federal Reserve Bank of Minneapolis. Research Department'
    term: 'Federal Reserve Bank of Minneapolis. Research Department'
    active: true
  - id: 'Federal Reserve Bank of Minneapolis. Research Division'
    term: 'Federal Reserve Bank of Minneapolis. Research Division'
    active: true
  - id: 'Federal Reserve Bank of Minneapolis. Institute for Empirical Macroeconomics'
    term: 'Federal Reserve Bank of Minneapolis. Institute for Empirical Macroeconomics'
    active: true
  - id: 'Federal Reserve Bank of Minneapolis. Opportunity and Inclusive Growth Institute'
    term: 'Federal Reserve Bank of Minneapolis. Opportunity and Inclusive Growth Institute'
    active: true
  - id: 'Federal Reserve Bank of Minneapolis. Economic Analysis'
    term: 'Federal Reserve Bank of Minneapolis. Economic Analysis'
    active: true
  - id: 'Federal Reserve Bank of Minneapolis. Community Development'
    term: 'Federal Reserve Bank of Minneapolis. Community Development'
