development:
  url: <%= ENV['SOLR_DEVELOPMENT_URL'] || 'http://127.0.0.1:8983/solr/hydra-development' %>
test:
  url: <%= ENV['SOLR_TEST_URL'] || 'http://127.0.0.1:8983/solr/hydra-test' %>
production:
  url: http://127.0.0.1:8983/solr/cypripedium
